import { expect, test } from 'bun:test';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

import {
  DEFAULT_CURSOR_MODEL,
  DEFAULT_GEMINI_MODEL,
  REPOLINE_SKILL_NAME,
  buildAgentEnvValues,
  buildFrontendEnvValues,
  loadEnvFile,
  loadSetupState,
  normalizeBridgeProvider,
  saveSetupState,
  writeEnvFile,
} from './bridge-runtime-config';

const REPO_ROOT = resolve(import.meta.dir, '..');

test('normalizeBridgeProvider keeps legacy aliases compatible', () => {
  expect(normalizeBridgeProvider('cursor-agent')).toBe('cursor');
  expect(normalizeBridgeProvider('CoDeX')).toBe('codex');
  expect(normalizeBridgeProvider('GeMiNi')).toBe('gemini');
  expect(normalizeBridgeProvider('unknown')).toBe('claude');
});

test('loadSetupState preserves legacy dispatch rule fields', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-config-'));
  const statePath = join(dir, 'state.json');
  writeFileSync(
    statePath,
    JSON.stringify({
      configured_at: '2026-04-11T00:00:00.000Z',
      livekit_project_name: 'demo',
      livekit_url: 'wss://example.livekit.cloud',
      agent_name: 'clawdbot-agent',
      bridge_provider: 'cursor-agent',
      workdir: '/tmp/project',
      phone: {
        number: '+15551234567',
        pin: '1234',
        dispatch_rule_name: 'Demo Rule',
        dispatch_rule_id: 'rule_123',
      },
    })
  );

  const state = loadSetupState(statePath);
  expect(state).not.toBeNull();
  expect(state?.bridge_provider).toBe('cursor');
  expect(state?.phone?.dispatchRuleName).toBe('Demo Rule');
  expect(state?.phone?.dispatchRuleId).toBe('rule_123');
});

test('writeEnvFile round-trips quoted values through loadEnvFile', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-env-'));
  const envPath = join(dir, '.env.local');
  writeEnvFile(envPath, {
    BRIDGE_SYSTEM_PROMPT: 'Speak "plainly" and keep paths like C:\\repo intact.',
    BRIDGE_MODEL: 'gpt-5-codex',
  });

  const env = loadEnvFile(envPath);
  expect(env.BRIDGE_SYSTEM_PROMPT).toBe('Speak "plainly" and keep paths like C:\\repo intact.');
  expect(env.BRIDGE_MODEL).toBe('gpt-5-codex');
  expect(readFileSync(envPath, 'utf8')).toContain('# Generated by `bun run setup`.');
});

test('buildFrontendEnvValues keeps a stable default app URL', () => {
  expect(
    buildFrontendEnvValues({
      project: {
        url: 'wss://example.livekit.cloud',
        apiKey: 'key',
        apiSecret: 'secret',
      },
      agentName: 'clawdbot-agent',
      existingFrontendEnv: {},
    })
  ).toMatchObject({
    LIVEKIT_URL: 'wss://example.livekit.cloud',
    LIVEKIT_API_KEY: 'key',
    LIVEKIT_API_SECRET: 'secret',
    AGENT_NAME: 'clawdbot-agent',
    NEXT_PUBLIC_APP_URL: 'http://localhost:3000',
  });
});

test('buildAgentEnvValues preserves direct speech provider env values', () => {
  expect(
    buildAgentEnvValues({
      project: {
        url: 'wss://example.livekit.cloud',
        apiKey: 'key',
        apiSecret: 'secret',
      },
      agentName: 'clawdbot-agent',
      bridgeProvider: 'cursor',
      workdir: '/tmp/demo',
      existingAgentEnv: {
        BRIDGE_STT_PROVIDER: 'deepgram',
        DEEPGRAM_API_KEY: 'deepgram-key',
        BRIDGE_TTS_PROVIDER: 'elevenlabs',
        ELEVENLABS_API_KEY: 'elevenlabs-key',
        ELEVENLABS_VOICE_ID: 'voice-123',
      },
    })
  ).toMatchObject({
    BRIDGE_MODEL: DEFAULT_CURSOR_MODEL,
    BRIDGE_CURSOR_TRANSPORT: 'cli',
    BRIDGE_CHUNK_CHARS: '80',
    BRIDGE_THINKING_SOUND_PRESET: 'soft-pulse',
    BRIDGE_THINKING_SOUND_INTERVAL_MS: '1800',
    BRIDGE_THINKING_SOUND_VOLUME: '0.11',
    BRIDGE_THINKING_SOUND_SIP_ONLY: 'true',
    BRIDGE_SHORT_TRANSCRIPT_WORDS: '2',
    BRIDGE_SHORT_TRANSCRIPT_DEBOUNCE_SECONDS: '0.55',
    BRIDGE_STT_PROVIDER: 'deepgram',
    DEEPGRAM_API_KEY: 'deepgram-key',
    BRIDGE_TTS_PROVIDER: 'elevenlabs',
    ELEVENLABS_API_KEY: 'elevenlabs-key',
    ELEVENLABS_VOICE_ID: 'voice-123',
  });
});

test('buildAgentEnvValues defaults Gemini to flash', () => {
  expect(
    buildAgentEnvValues({
      project: {
        url: 'wss://example.livekit.cloud',
        apiKey: 'key',
        apiSecret: 'secret',
      },
      agentName: 'clawdbot-agent',
      bridgeProvider: 'gemini',
      workdir: '/tmp/demo',
      existingAgentEnv: {},
    })
  ).toMatchObject({
    BRIDGE_MODEL: DEFAULT_GEMINI_MODEL,
    BRIDGE_CLI_PROVIDER: 'gemini',
  });
});

test('buildAgentEnvValues preserves cursor app transport', () => {
  expect(
    buildAgentEnvValues({
      project: {
        url: 'wss://example.livekit.cloud',
        apiKey: 'key',
        apiSecret: 'secret',
      },
      agentName: 'clawdbot-agent',
      bridgeProvider: 'cursor',
      workdir: '/tmp/demo',
      existingAgentEnv: {
        BRIDGE_CURSOR_TRANSPORT: 'app',
      },
    })
  ).toMatchObject({
    BRIDGE_CLI_PROVIDER: 'cursor',
    BRIDGE_MODEL: DEFAULT_CURSOR_MODEL,
    BRIDGE_CURSOR_TRANSPORT: 'app',
  });
});

test('buildAgentEnvValues preserves thinking sound overrides', () => {
  expect(
    buildAgentEnvValues({
      project: {
        url: 'wss://example.livekit.cloud',
        apiKey: 'key',
        apiSecret: 'secret',
      },
      agentName: 'clawdbot-agent',
      bridgeProvider: 'claude',
      workdir: '/tmp/demo',
      existingAgentEnv: {
        BRIDGE_THINKING_SOUND_PRESET: 'glass',
        BRIDGE_THINKING_SOUND_INTERVAL_MS: '0',
        BRIDGE_THINKING_SOUND_VOLUME: '0.22',
        BRIDGE_THINKING_SOUND_SIP_ONLY: 'false',
      },
    })
  ).toMatchObject({
    BRIDGE_THINKING_SOUND_PRESET: 'glass',
    BRIDGE_THINKING_SOUND_INTERVAL_MS: '0',
    BRIDGE_THINKING_SOUND_VOLUME: '0.22',
    BRIDGE_THINKING_SOUND_SIP_ONLY: 'false',
  });
});

test('ts-generated env loads through BridgeConfig.load in python', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-parity-'));
  const workdir = join(dir, 'repo');
  const skillPath = join(workdir, '.agents', 'skills', REPOLINE_SKILL_NAME, 'SKILL.md');
  mkdirSync(join(workdir, '.agents', 'skills', REPOLINE_SKILL_NAME), {
    recursive: true,
  });
  writeFileSync(
    skillPath,
    `---
name: ${REPOLINE_SKILL_NAME}
description: Example
---

Use short spoken replies.
`
  );

  const env = buildAgentEnvValues({
    project: {
      url: 'wss://example.livekit.cloud',
      apiKey: 'key',
      apiSecret: 'secret',
    },
    agentName: 'clawdbot-agent',
    bridgeProvider: 'codex',
    workdir,
    existingAgentEnv: {
      BRIDGE_ACCESS_POLICY: 'write',
      BRIDGE_CODEX_REASONING_EFFORT: 'medium',
    },
  });

  const script = `
import json
import sys
sys.path.insert(0, "agent/src")
from bridge_config import BridgeConfig
env = json.loads(sys.argv[1])
config = BridgeConfig.load(env, sys.argv[2])
print(json.dumps({
    "provider": config.provider,
    "access_policy": config.access_policy,
    "thinking_level": config.thinking_level,
    "skill_name": config.skill_name,
}, sort_keys=True))
`;
  const result = spawnSync(
    'uv',
    ['run', '--project', 'agent', 'python', '-c', script, JSON.stringify(env), dir],
    {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }
  );

  expect(result.status).toBe(0);
  expect(JSON.parse(result.stdout)).toEqual({
    access_policy: 'workspace-write',
    provider: 'codex',
    skill_name: REPOLINE_SKILL_NAME,
    thinking_level: 'medium',
  });
  expect(env.LIVEKIT_RECORD_AUDIO).toBe('false');
  expect(env.LIVEKIT_RECORD_TRACES).toBe('false');
  expect(env.LIVEKIT_RECORD_LOGS).toBe('false');
  expect(env.LIVEKIT_RECORD_TRANSCRIPT).toBe('false');
  expect(env.REPOLINE_ALLOW_OWNER).toBe('');
});

test('python BridgeConfig.load fails when generated env points at a missing skill', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-parity-missing-'));
  const workdir = join(dir, 'repo');
  mkdirSync(workdir, { recursive: true });

  const env = buildAgentEnvValues({
    project: {
      url: 'wss://example.livekit.cloud',
      apiKey: 'key',
      apiSecret: 'secret',
    },
    agentName: 'clawdbot-agent',
    bridgeProvider: 'codex',
    workdir,
    existingAgentEnv: {},
  });

  const script = `
import json
import sys
sys.path.insert(0, "agent/src")
from bridge_config import BridgeConfig
env = json.loads(sys.argv[1])
BridgeConfig.load(env, sys.argv[2])
`;
  const result = spawnSync(
    'uv',
    ['run', '--project', 'agent', 'python', '-c', script, JSON.stringify(env), dir],
    {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }
  );

  expect(result.status).not.toBe(0);
  expect(result.stderr).toContain('FileNotFoundError');
});

test('saveSetupState writes state that loadSetupState can read back', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-state-'));
  const statePath = join(dir, '.bridge', 'state.json');
  saveSetupState(statePath, {
    configured_at: '2026-04-11T00:00:00.000Z',
    livekit_project_name: 'demo',
    livekit_url: 'wss://example.livekit.cloud',
    agent_name: 'clawdbot-agent',
    bridge_provider: 'claude',
    workdir: '/tmp/project',
    phone: null,
  });

  expect(loadSetupState(statePath)).toEqual({
    configured_at: '2026-04-11T00:00:00.000Z',
    livekit_project_name: 'demo',
    livekit_url: 'wss://example.livekit.cloud',
    agent_name: 'clawdbot-agent',
    bridge_provider: 'claude',
    workdir: '/tmp/project',
    phone: null,
  });
});
