import { expect, test } from 'bun:test';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

import {
  REPOLINE_SKILL_NAME,
  buildAgentEnvValues,
  loadEnvFile,
  loadSetupState,
  normalizeBridgeProvider,
  saveSetupState,
  writeEnvFile,
} from './bridge-runtime-config';

const REPO_ROOT = resolve(import.meta.dir, '..');

test('normalizeBridgeProvider keeps legacy aliases compatible', () => {
  expect(normalizeBridgeProvider('cursor-agent')).toBe('cursor');
  expect(normalizeBridgeProvider('CoDeX')).toBe('codex');
  expect(normalizeBridgeProvider('unknown')).toBe('claude');
});

test('loadSetupState preserves legacy dispatch rule fields', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-config-'));
  const statePath = join(dir, 'state.json');
  writeFileSync(
    statePath,
    JSON.stringify({
      configured_at: '2026-04-11T00:00:00.000Z',
      livekit_project_name: 'demo',
      livekit_url: 'wss://example.livekit.cloud',
      agent_name: 'clawdbot-agent',
      bridge_provider: 'cursor-agent',
      workdir: '/tmp/project',
      phone: {
        number: '+15551234567',
        pin: '1234',
        dispatch_rule_name: 'Demo Rule',
        dispatch_rule_id: 'rule_123',
      },
    })
  );

  const state = loadSetupState(statePath);
  expect(state).not.toBeNull();
  expect(state?.bridge_provider).toBe('cursor');
  expect(state?.phone?.dispatchRuleName).toBe('Demo Rule');
  expect(state?.phone?.dispatchRuleId).toBe('rule_123');
});

test('writeEnvFile round-trips quoted values through loadEnvFile', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-env-'));
  const envPath = join(dir, '.env.local');
  writeEnvFile(envPath, {
    BRIDGE_SYSTEM_PROMPT: 'Speak "plainly" and keep paths like C:\\repo intact.',
    BRIDGE_MODEL: 'gpt-5-codex',
  });

  const env = loadEnvFile(envPath);
  expect(env.BRIDGE_SYSTEM_PROMPT).toBe('Speak "plainly" and keep paths like C:\\repo intact.');
  expect(env.BRIDGE_MODEL).toBe('gpt-5-codex');
  expect(readFileSync(envPath, 'utf8')).toContain('# Generated by `bun run setup`.');
});

test('ts-generated env loads through BridgeConfig.load in python', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-parity-'));
  const workdir = join(dir, 'repo');
  const skillPath = join(workdir, '.agents', 'skills', REPOLINE_SKILL_NAME, 'SKILL.md');
  mkdirSync(join(workdir, '.agents', 'skills', REPOLINE_SKILL_NAME), {
    recursive: true,
  });
  writeFileSync(
    skillPath,
    `---
name: ${REPOLINE_SKILL_NAME}
description: Example
---

Use short spoken replies.
`
  );

  const env = buildAgentEnvValues({
    project: {
      url: 'wss://example.livekit.cloud',
      apiKey: 'key',
      apiSecret: 'secret',
    },
    agentName: 'clawdbot-agent',
    bridgeProvider: 'codex',
    workdir,
    existingAgentEnv: {
      BRIDGE_ACCESS_POLICY: 'write',
      BRIDGE_CODEX_REASONING_EFFORT: 'medium',
    },
  });

  const script = `
import json
import sys
sys.path.insert(0, "agent/src")
from bridge_config import BridgeConfig
env = json.loads(sys.argv[1])
config = BridgeConfig.load(env, sys.argv[2])
print(json.dumps({
    "provider": config.provider,
    "access_policy": config.access_policy,
    "thinking_level": config.thinking_level,
    "skill_name": config.skill_name,
}, sort_keys=True))
`;
  const result = spawnSync(
    'uv',
    ['run', '--project', 'agent', 'python', '-c', script, JSON.stringify(env), dir],
    {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }
  );

  expect(result.status).toBe(0);
  expect(JSON.parse(result.stdout)).toEqual({
    access_policy: 'workspace-write',
    provider: 'codex',
    skill_name: REPOLINE_SKILL_NAME,
    thinking_level: 'medium',
  });
});

test('python BridgeConfig.load fails when generated env points at a missing skill', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-parity-missing-'));
  const workdir = join(dir, 'repo');
  mkdirSync(workdir, { recursive: true });

  const env = buildAgentEnvValues({
    project: {
      url: 'wss://example.livekit.cloud',
      apiKey: 'key',
      apiSecret: 'secret',
    },
    agentName: 'clawdbot-agent',
    bridgeProvider: 'codex',
    workdir,
    existingAgentEnv: {},
  });

  const script = `
import json
import sys
sys.path.insert(0, "agent/src")
from bridge_config import BridgeConfig
env = json.loads(sys.argv[1])
BridgeConfig.load(env, sys.argv[2])
`;
  const result = spawnSync(
    'uv',
    ['run', '--project', 'agent', 'python', '-c', script, JSON.stringify(env), dir],
    {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }
  );

  expect(result.status).not.toBe(0);
  expect(result.stderr).toContain('FileNotFoundError');
});

test('saveSetupState writes state that loadSetupState can read back', () => {
  const dir = mkdtempSync(join(tmpdir(), 'bridge-state-'));
  const statePath = join(dir, '.bridge', 'state.json');
  saveSetupState(statePath, {
    configured_at: '2026-04-11T00:00:00.000Z',
    livekit_project_name: 'demo',
    livekit_url: 'wss://example.livekit.cloud',
    agent_name: 'clawdbot-agent',
    bridge_provider: 'claude',
    workdir: '/tmp/project',
    phone: null,
  });

  expect(loadSetupState(statePath)).toEqual({
    configured_at: '2026-04-11T00:00:00.000Z',
    livekit_project_name: 'demo',
    livekit_url: 'wss://example.livekit.cloud',
    agent_name: 'clawdbot-agent',
    bridge_provider: 'claude',
    workdir: '/tmp/project',
    phone: null,
  });
});
